[package]
name = "aoc2023-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.98"
env_logger = "0.11.8"
log = "0.4.27"
once_cell = "1.21.3"
regex = "1.11.1"
