name: HOTLangBench CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '24'
    - name: Install prerequisites
      run: ./install-prereqs.sh
    - name: Build executables
      run: ./buildall.sh
    - name: Generate small benchmarks for testing
      run: |
        echo Generate full output
        ./runall.sh > output.txt
	echo Display output
	cat output.txt
	echo Show benchmark
        grep walltime output.txt
