name: HOTLangBench CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '24'
    - uses: actions/setup-go@v5
    - name: Install remaining prerequisites
      run: ./scripts/install-prereqs.sh
    - name: Build executables
      run: ./scripts/buildall.sh
    - name: Run benchmarks on small input
      run: |
        ./scripts/runall.sh
        echo ===========================
        echo ===== Show benchmarks =====
        echo ===========================
        cat dryrun-results.csv
