name: HOTLangBench CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '24.0.1'
    - name: Install prerequisites
      run: ./install-prereqs.sh
    - name: Build executables
      run: ./buildall.sh
    - name: Dryrun benchmarks on small input to cache library dependencies
      run: ./runall.sh
    - name: Run benchmarks again on small input
      run: |
        ./runall.sh > output.txt
        echo Display full output
        cat output.txt
        echo Show benchmarks
        grep walltime output.txt
