name: HOTLangBench CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '24.0.1'
    - uses: swift-actions/setup-swift@v2
    - uses: actions/setup-go@v5
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install remaining prerequisites
      run: ./scripts/install-prereqs.sh
    - name: Build executables
      run: ./scripts/buildall.sh
    - name: Dryrun benchmarks on small input to cache library dependencies
      run: ./scripts/runall.sh
    - name: Run benchmarks again on small input
      run: |
        ./scripts/runall.sh
        echo ===========================
        echo ===== Show benchmarks =====
        echo ===========================
        cat dryrun-results.csv
